development:
  adapter: mysql2
  encoding: utf8
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  database: email_service_development
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  database: email_service_test
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  database: email_service_production
  host: localhost